# site properties and page defaults
title: Zdouc Lab
subtitle: Where Microbial Natural Products Meet Data Science
description: The Zdouc research lab at the University of Vienna investigates naturally occurring, specialized molecules called natural products. These small molecules are widely used in medicine, food science, and agriculture, and are of enormous societal importance. Our investigation focuses on microbial natural products, which are especially promising for the development of new antibiotics.
header: images/header_sm.JPG
footer: images/footer_sm.JPG
proofer: false

# site social media and other links
links:
  email: mitja.zdouc@univie.ac.at
  github: zdouc-lab

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
